# Generated by Django 4.2 on 2023-07-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customeuser', '0002_customtoken'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
