# Generated by Django 4.2 on 2023-07-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customeuser', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
